---
# PHP installation for Debian jessie

- name: Install php
  apt: name=php5
  when: ansible_distribution_release == 'jessie'

- name: Install php command line interpreter
  apt: name=php5-cli
  when: ansible_distribution_release == 'jessie'

- name: Install php-mysql
  apt: name=php5-mysql
  when: ansible_distribution_release == 'jessie'

- name: Install apache php
  apt: name=libapache2-mod-php5
  when: ansible_distribution_release == 'jessie'

# PHP installation for Ubuntu 16.04 or Debian stretch

- name: Install php
  apt: name=php
  when: ansible_distribution_release != 'jessie'

- name: Install php command line interpreter
  apt: name=php-cli
  when: ansible_distribution_release != 'jessie'

- name: Install php-mysql
  apt: name=php-mysql
  when: ansible_distribution_release != 'jessie'

- name: Install apache php
  apt: name=libapache2-mod-php
  when: ansible_distribution_release != 'jessie'

# End of PHP installation


- name: Install unzip
  apt: name=unzip

- name: Install mysql
  apt: name=mysql-server

- name: Install python-mysqldb
  apt: name=python-mysqldb

- name: Check whether mysql root password is set
  shell: echo '\q' | mysql --user=root mysql
  register: connect_to_mysql_without_password
  check_mode: no
  ignore_errors: True
  changed_when: False

- name: Set mysql root password
  shell: >
    echo "SET PASSWORD for 'root'@'localhost' 
    = PASSWORD('{{ mysql_root_password}}');"
    | mysql --user=root mysql
  when: "connect_to_mysql_without_password.rc == 0"

- name: Create mysql wordpress user
  mysql_user:
    name: wordpress
    password: "{{ wordpress_db_password }}"
    priv: wordpress\_%.*:ALL,GRANT
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create wordpress database
  mysql_db:
    name: wordpress_{{ wordpress_installation_name }}
    encoding: "{{ wordpress_db_charset }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Backup MySQL
  template: src=backup-mysql.sh dest=/etc/duply/main/pre-scripts/mysql mode=0700
  when: duply_deactivate == false

- name: Install wordpress
  shell: >
    rm -rf /tmp/wp.tar.gz /tmp/wordpress &&
    wget -O /tmp/wp.tar.gz https://wordpress.org/latest.tar.gz &&
    cd /tmp &&
    tar xzf /tmp/wp.tar.gz &&
    mv /tmp/wordpress /var/opt/wordpress-{{ wordpress_installation_name }} &&
    chown -R www-data /var/opt/wordpress-{{ wordpress_installation_name }}
  args:
    creates: /var/opt/wordpress-{{ wordpress_installation_name }}

- name: Create config directory
  file: dest=/etc/wordpress state=directory

- name: Create wp-config.php
  template: src=wp-config.php dest=/etc/wordpress/wp-config-{{ wordpress_installation_name }}.php

- name: Link wp-config.php
  file:
    src: /etc/wordpress/wp-config-{{ wordpress_installation_name }}.php
    dest: /var/opt/wordpress-{{ wordpress_installation_name }}/wp-config.php
    state: link

- name: Create wp-uploads directory
  file:
    dest: /var/opt/wordpress-{{ wordpress_installation_name }}/wp-content/uploads
    owner: www-data
    state: directory

- name: Install themes
  git:
    repo: "{{ item.value }}"
    dest: /var/opt/wordpress-{{ wordpress_installation_name }}/wp-content/themes/{{ item.key }}
    ssh_opts: '-o StrictHostKeyChecking=no'
  with_dict: "{{ wordpress_themes }}"

- name: Setup apache for wordpress
  template:
    src: apache-wordpress.conf 
    dest: /etc/apache2/snippets/{{ wordpress_domain }}/wordpress-{{ wordpress_installation_name }}.conf
  notify:
  - Restart apache
